insert into ACT_GE_SCHEMA_LOG values ('201', CURRENT_TIMESTAMP, '7.13.5_1');

create index ACT_IDX_TASK_OWNER on ACT_RU_TASK(OWNER_);


insert into ACT_GE_SCHEMA_LOG values ('202', CURRENT_TIMESTAMP, '7.13.5_2');

create index ACT_IDX_HI_INCIDENT_CREATE_TIME on ACT_HI_INCIDENT(CREATE_TIME_);
create index ACT_IDX_HI_INCIDENT_END_TIME on ACT_HI_INCIDENT(END_TIME_);

insert into ACT_GE_SCHEMA_LOG values ('203', CURRENT_TIMESTAMP, '7.13.6');
insert into ACT_GE_PROPERTY values ('telemetry.lock', '0', 1);
insert into ACT_GE_PROPERTY values ('installationId.lock', '0', 1);



insert into ACT_GE_SCHEMA_LOG values ('300', CURRENT_TIMESTAMP, '7.14.0');

ALTER TABLE ACT_RU_VARIABLE ADD BATCH_ID_ varchar(64);

CREATE INDEX ACT_IDX_BATCH_ID ON ACT_RU_VARIABLE(BATCH_ID_);

ALTER TABLE ACT_RU_VARIABLE
    ADD CONSTRAINT ACT_FK_VAR_BATCH
    FOREIGN KEY (BATCH_ID_)
    REFERENCES ACT_RU_BATCH (ID_);

create index ACT_IDX_VARIABLE_TASK_NAME_TYPE on ACT_RU_VARIABLE(TASK_ID_, NAME_, TYPE_);